name: Validate PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate Pull Request title
    runs-on: ubuntu-latest
    steps:
      - name: Check that PR title conforms to conventional commits format
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            ci
            chore
          requireScope: false
          subjectPattern: '^[^A-Z].*[^.]$' # PR title should not start with a capital letter and should not end with a period
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with a capital letter and doesn't end with a period.
          validateSingleCommit: true
